Patch the K8s service to expose the UI port
canonical/karma-operator pull request #3
Opened 2021-08-19 09:30 UTC by mmanciop

2021-08-19 09:34 UTC, jnsgruk approved these changes

2021-08-19 15:28 UTC, sed-i requested changes
Same comment as in alertmanager:
https://github.com/canonical/alertmanager-operator/pull/28#pullrequestreview-734157719

As part of this change, can you please get rid of `_stored.k8s_service_patched`?
It seems that we only call it when it needs to be called anyway.
I originally had `k8s_service_patched` when I was calling the patch from within _common_exit_hook.

2021-08-20 07:57 UTC, jnsgruk approved these changes

2021-08-20 07:57 UTC, jnsgruk commented on src/charm.py
> +                logger.info("Successfully patched the Kubernetes service!")
```suggestion
                logger.info("Successfully patched the Kubernetes service")
```

2021-08-20 13:57 UTC, sed-i approved these changes

2021-08-20 13:58 UTC, merged